import React, { useState } from 'react';

const COMPOUND_BADGES = {
  SOFT: 'bg-red-600 text-white',
  MEDIUM: 'bg-amber-500 text-black font-extrabold',
  HARD: 'bg-zinc-100 text-black font-extrabold',
  INTERMEDIATE: 'bg-emerald-600 text-white',
  WET: 'bg-blue-600 text-white',
};

const formatRaceTime = (secs) => {
  if (!secs) return '--';
  const mins = Math.floor(secs / 60);
  const remSecs = (secs % 60).toFixed(2);
  return `${mins}m ${remSecs.padStart(5, '0')}s`;
};

const CandidateStrategiesTable = ({ candidateStrategies = [], recommendedPitLap, recommendedCompound }) => {
  const [sortKey, setSortKey] = useState('projectedRaceTimeSec');
  const [sortOrder, setSortOrder] = useState('asc');

  if (!candidateStrategies || !candidateStrategies.length) {
    return (
      <div className="bg-zinc-950/80 backdrop-blur-md border border-zinc-800/80 rounded-xl p-4 h-full flex flex-col items-center justify-center text-center">
        <div className="w-10 h-10 rounded-full bg-zinc-900 border border-zinc-800 flex items-center justify-center text-zinc-500 text-lg font-bold mb-2">
          📋
        </div>
        <h4 className="text-xs font-bold text-white font-inter uppercase tracking-wider mb-1">
          No strategy generated.
        </h4>
        <p className="text-[11px] text-zinc-400 font-tech-mono max-w-xs">
          Candidate options evaluated by the strategy simulator will populate here.
        </p>
      </div>
    );
  }

  const optimalTime = Math.min(...candidateStrategies.map((c) => c.projectedRaceTimeSec || Infinity));

  const handleSort = (key) => {
    if (sortKey === key) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
    } else {
      setSortKey(key);
      setSortOrder('asc');
    }
  };

  const sortedCandidates = [...candidateStrategies].sort((a, b) => {
    let valA = a[sortKey];
    let valB = b[sortKey];
    if (valA < valB) return sortOrder === 'asc' ? -1 : 1;
    if (valA > valB) return sortOrder === 'asc' ? 1 : -1;
    return 0;
  });

  return (
    <div 
      className="bg-zinc-950/80 backdrop-blur-md border border-zinc-800/80 rounded-xl p-4 shadow-lg shadow-black/40 flex flex-col h-full"
      aria-label="Candidate Strategy Options Evaluated by Strategy Simulator"
    >
      <div className="flex items-center justify-between mb-3 border-b border-zinc-800/80 pb-2.5">
        <div>
          <h3 className="text-xs font-bold text-white uppercase tracking-wider font-inter">
            Candidate Strategy Matrix
          </h3>
          <p className="text-[11px] text-zinc-400 font-inter mt-0.5">
            Generated by strategy simulation (evaluating pit windows & compound choices).
          </p>
        </div>
        <span className="text-[10px] font-tech-mono text-zinc-400 bg-zinc-900 px-2 py-0.5 rounded border border-zinc-800">
          {candidateStrategies.length} Options Evaluated
        </span>
      </div>

      <div className="overflow-x-auto overflow-y-auto max-h-72 rounded-lg border border-zinc-800/80">
        <table className="w-full text-left text-xs border-collapse" tabIndex={0} role="grid">
          <thead className="sticky top-0 bg-zinc-900/95 text-zinc-400 font-tech-mono uppercase tracking-wider text-[9px] border-b border-zinc-800">
            <tr>
              <th
                className="py-2.5 px-3 cursor-pointer hover:text-white transition-colors"
                onClick={() => handleSort('pitLap')}
              >
                Pit Lap {sortKey === 'pitLap' ? (sortOrder === 'asc' ? '▲' : '▼') : ''}
              </th>
              <th
                className="py-2.5 px-3 cursor-pointer hover:text-white transition-colors"
                onClick={() => handleSort('targetCompound')}
              >
                Compound {sortKey === 'targetCompound' ? (sortOrder === 'asc' ? '▲' : '▼') : ''}
              </th>
              <th
                className="py-2.5 px-3 cursor-pointer hover:text-white transition-colors"
                onClick={() => handleSort('projectedRaceTimeSec')}
              >
                Projected Duration {sortKey === 'projectedRaceTimeSec' ? (sortOrder === 'asc' ? '▲' : '▼') : ''}
              </th>
              <th className="py-2.5 px-3">Delta vs Optimal</th>
              <th
                className="py-2.5 px-3 cursor-pointer hover:text-white transition-colors"
                onClick={() => handleSort('expectedTyreLifeAtPit')}
              >
                Tyre Life {sortKey === 'expectedTyreLifeAtPit' ? (sortOrder === 'asc' ? '▲' : '▼') : ''}
              </th>
              <th className="py-2.5 px-3">Expected Pace</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-zinc-800/50 font-tech-mono text-zinc-300">
            {sortedCandidates.map((cand, idx) => {
              const isRecommended =
                cand.pitLap === recommendedPitLap &&
                cand.targetCompound?.toUpperCase() === recommendedCompound?.toUpperCase();

              const deltaSec = (cand.projectedRaceTimeSec - optimalTime).toFixed(2);

              return (
                <tr
                  key={`${cand.pitLap}-${cand.targetCompound}-${idx}`}
                  tabIndex={0}
                  className={`transition-colors ${
                    isRecommended
                      ? 'bg-red-950/40 text-white font-bold border-l-4 border-l-red-600'
                      : 'hover:bg-zinc-900/60 focus:bg-zinc-900/80 outline-none'
                  }`}
                >
                  <td className="py-2 px-3">
                    <div className="flex items-center gap-1.5">
                      <span>Lap {cand.pitLap}</span>
                      {isRecommended && (
                        <span className="text-[8px] bg-red-600 text-white px-1.5 py-0.5 rounded font-bold uppercase orbitron">
                          OPTIMAL PLAN
                        </span>
                      )}
                    </div>
                  </td>
                  <td className="py-2 px-3">
                    <span
                      className={`inline-block px-2 py-0.5 rounded text-[9px] uppercase font-bold ${
                        COMPOUND_BADGES[cand.targetCompound?.toUpperCase()] || 'bg-zinc-800 text-white'
                      }`}
                    >
                      {cand.targetCompound}
                    </span>
                  </td>
                  <td className="py-2 px-3">
                    <div className="flex flex-col">
                      <span className={isRecommended ? 'text-emerald-400 font-bold' : ''}>
                        {formatRaceTime(cand.projectedRaceTimeSec)}
                      </span>
                      <span className="text-[9px] text-zinc-500">{cand.projectedRaceTimeSec?.toFixed(2)}s</span>
                    </div>
                  </td>
                  <td className="py-2 px-3">
                    {Number(deltaSec) === 0 ? (
                      <span className="text-emerald-400 font-bold">+0.00 s (Optimal)</span>
                    ) : (
                      <span className="text-amber-400 font-medium">+{deltaSec} s</span>
                    )}
                  </td>
                  <td className="py-2 px-3">
                    {cand.expectedTyreLifeAtPit ?? '--'} Laps
                  </td>
                  <td className="py-2 px-3 text-zinc-400">
                    {cand.avgPaceAfterPit ? `${cand.avgPaceAfterPit.toFixed(2)}s` : '--'}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default CandidateStrategiesTable;
